// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package wechatwidget.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;

public class JA_WXPay extends CustomJavaAction<java.lang.Void>
{
	private java.lang.String appid;
	private java.lang.String mchid;
	private java.lang.String private_key;
	private java.lang.String serial_no;
	private java.lang.String apiv3_key;
	private java.math.BigDecimal total;
	private java.lang.String description;
	private java.lang.String openid;

	public JA_WXPay(IContext context, java.lang.String appid, java.lang.String mchid, java.lang.String private_key, java.lang.String serial_no, java.lang.String apiv3_key, java.math.BigDecimal total, java.lang.String description, java.lang.String openid)
	{
		super(context);
		this.appid = appid;
		this.mchid = mchid;
		this.private_key = private_key;
		this.serial_no = serial_no;
		this.apiv3_key = apiv3_key;
		this.total = total;
		this.description = description;
		this.openid = openid;
	}

	@java.lang.Override
	public java.lang.Void executeAction() throws Exception
	{
		// BEGIN USER CODE
		throw new com.mendix.systemwideinterfaces.MendixRuntimeException("Java action was not implemented");
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "JA_WXPay";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
