// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import { Big } from "big.js";
import wx from 'weixin-js-sdk'
import { callMicroflow } from '../utils'

// BEGIN EXTRA CODE

// END EXTRA CODE

/**
 * @param {string} appId
 * @param {string} nonce
 * @param {string} timestamp
 * @param {string} sig
 * @returns {Promise.<string>}
 */
export async function WX_JS_ScanQR(appId, nonce, timestamp, sig) {
	// BEGIN USER CODE

  wx.miniProgram.getEnv(function (res) {
    console.log(res.miniprogram) // true
  })

  return new Promise((resolve, reject) => {
    wx.config({
      debug: false,
      appId,
      timestamp,
      nonceStr: nonce,
      signature: sig,
      jsApiList: ['scanQRCode'],
    })

    wx.ready(function () {
      wx.scanQRCode({
        needResult: 1, // 默认为0，扫描结果由微信处理，1则直接返回扫描结果，
        scanType: ['qrCode', 'barCode'], // 可以指定扫二维码还是一维码，默认二者都有
        success: function (res) {
          var result = res.resultStr // 当needResult 为 1 时，扫码返回的结果
          resolve(result)
        },
      })
    })

    wx.error(function (res) {
      console.log(res)
    })
  })

	// END USER CODE
}
