// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import { Big } from "big.js";
import wx from 'weixin-js-sdk'
import { callMicroflow } from '../utils'

// BEGIN EXTRA CODE

// END EXTRA CODE

/**
 * @param {string} appId
 * @param {string} nonce
 * @param {string} timestamp
 * @param {string} sig
 * @returns {Promise.<string>}
 */
export async function WX_JS_Camera(appId, nonce, timestamp, sig) {
	// BEGIN USER CODE

  wx.miniProgram.getEnv(function (res) {
    console.log(res.miniprogram) // true
  })

  return new Promise((resolve, reject) => {
    wx.config({
      debug: false,
      appId,
      timestamp,
      nonceStr: nonce,
      signature: sig,
      jsApiList: [
        'chooseImage',
        'previewImage',
        'uploadImage',
        'downloadImage',
      ],
    })

    const getImageData = (localIDList) => {
      let imageDataList = []
      return new Promise((resolve, reject) => {
        for (let localID of localIDList) {
          wx.getLocalImgData({
            localId: localID,
            success: function (res) {
              imageDataList.push({
                base64: res.localData,
              })
            },
          })
        }
        resolve(imageDataList)
      })
    }

    wx.ready(function () {
      wx.chooseImage({
        count: 9, // 默认9
        sizeType: ['original', 'compressed'],
        sourceType: ['album', 'camera'],
        success: async (res) => {
          var localIds = res.localIds
          // const imageDataList = await getImageData(localIds)
          wx.getLocalImgData({
            localId: res.localIds[0],
            success: function (res) {
              const localData = res.localData
              resolve(localData)
              // if (localData.indexOf('data:image') == 0) {
              //   imageBase64 = localData
              //   callMicroflow('WeChatWidget.SMP_ShowImagePage', imageBase64)
              // } else {
              //   imageBase64 =
              //     'data:image/jpeg;base64,' + localData.replace(/\n/g, '')
              //   callMicroflow('WeChatWidget.SMP_ShowImagePage', imageBase64)
              // }
            },
          })
          // wx.uploadImage({
          //   localId: localIds[0],
          //   isShowProgressTips: 1,
          //   success: function (res) {
          //     wx.miniProgram.navigateTo({url: '../image/image?id=' + encodeURIComponent(res.serverId)})
          //   },
          // })
          // return imageDataList[0]
        },
        error: function (res) {
          console.log(res)
        },
      })
    })

    wx.error(function (res) {
      console.log(res)
    })
  })

	// END USER CODE
}
