// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import { Big } from "big.js";
import wx from 'weixin-js-sdk'

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * @param {string} appId
 * @param {string} nonce
 * @param {string} timestamp
 * @param {string} sig
 * @returns {Promise.<MxObject>}
 */
export async function WX_JS_GetCurrentLocation(appId, nonce, timestamp, sig) {
	// BEGIN USER CODE

  wx.miniProgram.getEnv(function (res) {
    console.log(res.miniprogram) // true
  })

  return new Promise((resolve, reject) => {
   wx.config({
      debug: false,
      appId,
      timestamp,
      nonceStr: nonce,
      signature: sig,
      jsApiList: ['openLocation', 'getLocation'],
    })

    wx.ready(() => {
      wx.getLocation({
        type: 'wgs84',
        success(res) {
          console.log(res)
          mx.data.create({
            entity: 'WeixinWidget.Location',
            callback: (location) => {
              location.set('latitude', Big(res.latitude).toFixed(6))
              location.set('longitude', Big(res.longitude).toFixed(6))
              location.set('title', '我的位置')
              resolve(location)         
            }
          })
          // wx.openLocation({
          //   latitude: res.latitude,
          //   longitude: res.longitude,
          //   scale: 18,
          //   name: '我的位置',
          // })
        },
        fail(res) {
          reject("could not get localtion")
        }
      })
    })

    wx.error(function (res) {
      console.log(res)
    })
  })

	// END USER CODE
}
